baseURL = "https://jtaka1012.github.io/sgl-hugo/"
theme = 'PaperMod'
title = 'Simple gadget life'

[params]
ShowBreadCrumbs = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
