baseURL = "https://jtaka1012.github.io/sgl-hugo/"
languageCode = "ja-jp"
title = "Simple gadget life"
theme = "PaperMod"

[params]
ShowBreadCrumbs = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
